### ISSUE TITLE
Do we have Application level interface in Insight?

### ISSUE THREAD

**Issue by roversmanoj** [CognizantOneDevOps/Insights#19]
hi,

how can one derive application/product quality metrics where an application has 10 services  & each services has multiple components, is there are way we can aggregate the quality metrics related to build, deployment, code quality etc across different sprints ?

Regards,
Manoj.

**Comment by rajkumarc2000** [comment]
Yes we do have a concept of Data tagging which helps to tag certain specific type of nodes for application so that we can application type of metrics. This section is undergoing change and it is likely to be available in the next couple of weeks. Please watch for our release update. In order to track this enhancement - we will keep this issue open in GitHub as well.

**Comment by rajkumarc2000** [comment]
The interface is ready and there are changes to the agent to do the data tagging during the data creation. The application level hierarchy can be created in the UI by uploading a excel sheet which contains the application level details. Testing is in progress - but you can take a look at the changes which are being made here. Once it is complete it will be merged to the master branch. 
https://github.com/CognizantOneDevOps/Insights/commits/DataTagging
