### ISSUE TITLE
The Postgres database for user profile management does not have the required tables.

### ISSUE THREAD

**Issue by gjerin594** [CognizantOneDevOps/Insights#97]
After following the steps mentioned in the official documentation at https://onedevops.atlassian.net/wiki/spaces/OI/pages/160202755/Insights+Architecture , there was a step for running a query against the DB in the application server to register the Daemon agent. However, there were no relations in the Postgres database and we were unable to find any mentions of a DB Script to create such a table.

![insights_github_issue_postgres](https://user-images.githubusercontent.com/40206308/41638909-60a2ba24-7479-11e8-85d9-7567ffbfaa40.png)

**Comment by vishwajitmankar** [comment]
Tables are created after you deploy WAR file successfully through Hibernate. Hope your WAR has deployed correctly. Please verify.

**Comment by nisanthjs** [comment]
Hi vishwajitmankar,
	For the war deployment, we followed the documentation and ran the script, insights_tomcat8.sh. After tomcat startup, in the log file, 'apache-tomcat-8.5.27/logs/PlatformService/log.out' we do see an error "javax.validation.ValidationException: Unable to create a Configuration, because no Bean Validation provider could be found. Add a provider like Hibernate Validator (RI)
 to your classpath." We have also attached the logs for your reference. As per our understanding this is due to a missing dependency and we have some queries regarding the same.
 
 1. Can we use the PlatformService.war from the link, http://platform.cogdevops.com/insights_install/release/latest/PlatformService.war directly for deployments, or we have to do a build of the war file from our end for deployments.
 2. Based on the above mentioned error, do you see any configuration that was missed?
 3. If the war file can be used directly from the above mentioned link, is this an open issue that is being worked upon.
 
 Insight's version : v4.1
 OS : Red Hat Enterprise Linux Server 7.5
 
 Thanks
[platformservice.log](https://github.com/CognizantOneDevOps/Insights/files/2119536/platformservice.log)

**Comment by vishwajitmankar** [comment]
You can ignore Hibernate validator error. It should not cause the issue. Also ignore the Db script entry for now. Login to application using admin/admin and check whether you are getting everything,

**Comment by nisanthjs** [comment]
Thanks vishwajitmankar for the response. We did try logging in to the Insights app using admin/admin. But it just keeps on loading and is stuck at the login page itself. When we analyzed the tomcat logs (attached as well) we could see the error - "java.lang.NoSuchMethodError: javax.ws.rs.core.NewCookie.<init>(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;ILjava/lang/String;ILjava/util/D
ate;ZZ)" . Is it a known issue? Please advise.

Please see attached tomcat start-up log (catalina_out-on-tomcat-startup.log) and Insights UI access log (localhost.2018-06-21.log) for your reference. 
[catalina_out-on-tomcat-startup.log](https://github.com/CognizantOneDevOps/Insights/files/2122236/catalina_out-on-tomcat-startup.log)
[localhost.2018-06-21.log](https://github.com/CognizantOneDevOps/Insights/files/2122238/localhost.2018-06-21.log)

 Thanks.

**Comment by vishwajitmankar** [comment]
Run below query in PostgreSQL as work around. 
INSERT INTO public.tools_layout(id, settings_json, tool_category, tool_name)  VALUES  (11,'{}','ALM','HP');

This functionality is not required anymore. We have already fixed it in master and will be available in next release. 
You can also build the artifacts from Master and use it.

**Comment by gjerin594** [comment]
After running the above query, this is the output that we are getting. It seems that there are no tables created in the Postgres DB.
![image](https://user-images.githubusercontent.com/40206308/41762490-8fff5160-7618-11e8-976c-8e2a00378044.png)

**Comment by vishwajitmankar** [comment]
Try to build WAR from Master and deploy it. It should work.

**Comment by gjerin594** [comment]
@vishwajitmankar Could you please mention when we can expect the next release for the Insights application?

**Comment by nisanthjs** [comment]
@vishwajitmankar ,  We noticed that when the PlatformService.war is built the below resources (that are available in GitHub) are not available in the war file. Even for the new build that we tried from master we observed the same. In catalina.out, we do see "2018-06-22 11:58:27 ERROR InsightsConfiguration:122 - Unable to read resources : layouts.java.lang.NullPointerException". So is this expected or are we missing them in war file. Please confirm.

- Insights/PlatformService/src/main/resources/layouts/
- Insights/PlatformService/src/main/resources/dashboards/

Also please let us know when the latest version will be available so that we can try out the same.

Thanks

**Comment by vishwajitmankar** [comment]
Next release will be available next week.

**Comment by gjerin594** [comment]
@vishwajitmankar - We can see that queues are getting created in the rabbitmq UI, also the tracking.Json is getting populated with the values from the base end point. However, we could not see any relations being made in the neo4j instance. What resolution or troubleshooting steps can we take to get the data into the neo4j database?

**Comment by SashikalaV** [comment]
Data not getting loaded to Neo4j? If yes, can you check for ERRORs in  PlatformEngine jar

**Comment by gjerin594** [comment]
We could see that the credentials for the InSights UI are being taken from the Postgres DB for grafana. We were looking in the Postgres DB for insights. Got the hint from one of the closed issues. Cheers! 

https://github.com/CognizantOneDevOps/Insights/issues/1
